//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikWebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Id { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
    }
}
