//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikWebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> UrunKategori { get; set; }
        public string UrunMarka { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public Nullable<byte> Stok { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
